language: java
jdk:
  - oraclejdk8
  - openjdk7
  - openjdk8

stages:
  - test
  - name: deploySnapshot
    if: branch = develop
  - name: deployRelease
    if: tag IS present

before_install:
  - if [ ! -z "$GPG_SECRET_KEYS" ]; then echo $GPG_SECRET_KEYS | base64 --decode | $GPG_EXECUTABLE --import; fi
  - if [ ! -z "$GPG_OWNERTRUST" ]; then echo $GPG_OWNERTRUST | base64 --decode | $GPG_EXECUTABLE --import-ownertrust; fi

install:
  - mvn --settings .travis/settings.xml install -Dgpg.skip -Dmaven.javadoc.skip=true -B -V

script: skip

jobs:
  include:
    - stage: deploySnapshot
      install: skip
      script: skip
      deploy:
        provider: script
        script: .travis/deploy.sh
        skip_cleanup: true
        on:
          repo: robotframework/MavenPlugin
          branch: develop
          jdk: oraclejdk8
    - stage: deployRelease
      install: skip
      script: skip
      deploy:
        provider: script
        script: .travis/deploy.sh
        skip_cleanup: true
        on:
          repo: robotframework/MavenPlugin
          tags: true
          jdk: oraclejdk8